# Generated by Django 2.1.4 on 2019-12-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportingHistory',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='reporting_id', primary_key=True, serialize=False)),
                ('requester_id', models.CharField(max_length=200)),
                ('requester_user_name', models.CharField(max_length=200)),
                ('message_slack_ts', models.CharField(blank=True, max_length=200, null=True)),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_name', models.CharField(max_length=150)),
                ('jira_card_id', models.CharField(blank=True, max_length=200, null=True)),
                ('jira_status', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'db_table': 'reporting_history',
            },
        ),
    ]
