# Generated by Django 2.1.4 on 2020-01-04 08:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_auto_20191229_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureSetting',
            fields=[
                ('cdate', models.DateTimeField(auto_now_add=True)),
                ('udate', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(db_column='feature_setting_id', primary_key=True, serialize=False)),
                ('feature_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('parameters', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'feature_setting',
            },
        ),
    ]
